### ISSUE TITLE
Renovate

### ISSUE THREAD

**Issue by luckasRanarison** [BetaX-Community/editor#4]
I think this repo could benefit from some updates, we could use modern bundlers like [vite](https://github.com/vitejs/vite) and update react to remove unnecessary bloat and dependencies.

And optionally typescript would be a plus, what do you guys think?

(Also, I can't "afford" installing apps made with CRA...)

**Comment by luckasRanarison** [comment]
> Please feel free to go for it!
I'll try that...

> What CRA.. are you talking about :rofl: ?
Projects made with `create-react-app` need A LOT of dependencies, about 200mb of data needed vs vite which just take 25~30mb. Also the dev server is really slow compared to vite.

**Comment by puchka** [comment]
I will try on my side as well.

I will create a new app with Vite and copy the JSX/JS files there to see how it works.

**Comment by puchka** [comment]
First iteration of the renovation has been done in #7

**Comment by puchka** [comment]
We can now

- [x] List bus lines
- [x] List bus stops
- [x] Filter bus lines
- [x] Filter bus stops
- [x] Display bus lines in the map

The next step is to
- [ ] List bus stops that are part of a bus line
- [ ] Display bus stops in the map on click

**Comment by puchka** [comment]
IMHO, this can be considered done.
